services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: todo_app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: postgres:16
    container_name: todo_db
    env_file: .env
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  todo_pg_data: